### ISSUE TITLE
Student Login, Select Courses, Select/Change Seating

### ISSUE THREAD

**Issue by dsteen338** [SWE-4103-Group-3/Project#11]
As a student, I need to login so that I can select my courses from a list and choose my seats for each course. I will choose one seat and it will be assigned to me for the rest of the course, unless I choose to move later.

Not all of my courses are necessarily listed - just the ones for which my instructor has decided to use this tool.

**Comment by jsmith** [comment]
I broke this issue down into two new issues #43 #42
