### ISSUE TITLE
Instructors track attendance through a table/spreadsheet

### ISSUE THREAD

**Issue by dsteen338** [SWE-4103-Group-3/Project#18]
As an instructor I need to be able to view a table which lists student in rows and Lecture dates (MMM-DD) in columns, and Xs in cells where studends were absent, so I can track attendance

I also need to store this information in a report that I can store outside the system

**Comment by dsteen338** [comment]
Estimate updated to 13

**Comment by dsteen338** [comment]
Estimate updated to 21

**Comment by brandon1024** [comment]
@JoshuaKirby @Korbos @dsteen338 @clayforeman 

We will need to arrange to meet up soon to discuss and plan out this issue. It would be nice to get this issue complete and PR open by EOD next tuesday.

**Comment by dsteen338** [comment]
Agreed. Tomorrow evening (post 630 or so) would be good for me

**Comment by dsteen338** [comment]
Can this be closed?

**Comment by jsmith** [comment]
Yeah, I think so!
