### ISSUE TITLE
Create Course Page

### ISSUE THREAD

**Issue by dsteen338** [SWE-4103-Group-3/Project#21]
Includes field for Course Name/ Code,  Course Section.
Radio button for either using existing template, or creating new template.
If new template must enter two values to create N*M starting grid to make seat template

**Comment by brandon1024** [comment]
This issue follows from [SWE8](https://github.com/SWE-4103-Group-3/Project/issues/8).

Instructor should be able to choose an existing template.

**Comment by jsmith** [comment]
Closing this issue and opening a new issue for using old templates #57
