### ISSUE TITLE
Student Class View

### ISSUE THREAD

**Issue by dsteen338** [SWE-4103-Group-3/Project#23]
Once student selects a course to view,  they can select a reservable seat and choose to reserve it.  
They can always reserve a new reservable seat, but they cannot unreserve themselves and not appear in the class altogether.

Students can see the names on seats that have already been reserved, and will not have option to reserve seats thatare Open, Closed, or already reserved

The students current seat can be highlighted

**Comment by jsmith** [comment]
Can this issue be closed?

**Comment by tonerm43** [comment]
Fixed by #84
