### ISSUE TITLE
Brochure

### ISSUE THREAD

**Issue by dsteen338** [SWE-4103-Group-3/Project#24]

**Comment by JDgriggs** [comment]
I've attached what I've done so far. The tone is a little less formal, as usually brochures are friendly and designed to sell a product. I can change it though if it's too cheesy. Though there's really only so much someone can say about the application at this point without repeating themselves. 

The Brochure template has a few spots for pictures but so far the only picture we really have is the one in the overview. I've added that to the brochure but if anybody has some kind of early design of the UI elements I can add those in place of the stock images. 

Let me know what you all think. Any feedback or suggestion is appreciated. 

[Brochure.docx](https://github.com/SWE-4103-Group-3/Project/files/1347031/Brochure.docx)

**Comment by JDgriggs** [comment]
PDF version as well.
[Brochure.pdf](https://github.com/SWE-4103-Group-3/Project/files/1347037/Brochure.pdf)
