### ISSUE TITLE
Jtwig Hot Reload

### ISSUE THREAD

**Issue by jsmith** [SWE-4103-Group-3/Project#31]
We should probably get hot reload working for the Jtwig by this coming Tuesday.

There is an example project which can be found [here](https://github.com/jtwig/jtwig-examples/tree/master/maven-jtwig-spring-boot-hot-reloading-extension).

**Comment by dsteen338** [comment]
By hot reload do you mean the ability to change the template without having to restart the server while developing? Or something else

**Comment by jsmith** [comment]
Yeah that's what I mean! I should have clarified

**Comment by dsteen338** [comment]
Do you think you have time to tackle this one?

**Comment by jsmith** [comment]
Yeah, I can definitely tackle this it won't take too long

**Comment by dsteen338** [comment]
Any progress?

**Comment by jsmith** [comment]
I haven't done anything yet, I was seeing if anyone else wanted to try! I'll just do it tomorrow though I think you just need to add a dependency

**Comment by jsmith** [comment]
This doesn't seem like it's going to work
