### ISSUE TITLE
Instructor/Student Views

### ISSUE THREAD

**Issue by mwalz1** [SWE-4103-Group-3/Project#4]
As an instructor, I need to be able to see the seating plan (seating template with reserved seats indicated by name) for all my courses so that I can associate names to seats when I am in lecture, and can record students who are absent

As a student, I need to be able to the see the seating plan (seating template with reserved seats indicated by name) so that I can choose a reserved seat in the class, somewhere by my friends

#### Subtasks:
[Student Class View](https://github.com/SWE-4103-Group-3/Project/issues/23)
[List of Courses View](https://github.com/SWE-4103-Group-3/Project/issues/34)

**Comment by brandon1024** [comment]
@jacsmith21 Can this be closed now?

**Comment by jsmith** [comment]
Yeah I think this should be closed
