### ISSUE TITLE
Test for Endpoints

### ISSUE THREAD

**Issue by jsmith** [SWE-4103-Group-3/Project#46]
Tests should be added for existing code in develop

**Comment by jsmith** [comment]
@dsteen338 Do think it be a good idea to write a short "How to Test in Spring" wiki page?

**Comment by dsteen338** [comment]
I think that's a great idea.

**Comment by jsmith** [comment]
Awsome! Do you want to create that page?

I'll add some tests for the JavaScript and will probably create a javascript testing page too!

**Comment by dsteen338** [comment]
Yep, I'll start working on it.

**Comment by dsteen338** [comment]
https://github.com/SWE-4103-Group-3/Project/wiki/Testing-in-springboot

**Comment by jsmith** [comment]
Love it, that's perfect!

**Comment by dsteen338** [comment]
@tonerm43 should this be assigned to you?

**Comment by brandon1024** [comment]
Fixed #59
