### ISSUE TITLE
Mobile Testing

### ISSUE THREAD

**Issue by jsmith** [SWE-4103-Group-3/Project#47]
As a student user, I want to be able to choose my seat on my phone.

**Comment by Korbos** [comment]
# **The mobile view is kinda zoomed out. You can still see, and you can pinch-to-zoom on it, but if we can, can we set it so the size is dynamic, so it scales to the size of the window it's displayed on?**
![screenshot_2017-10-16-08-35-40](https://user-images.githubusercontent.com/16106413/31610164-76d775d0-b24d-11e7-9039-909525890ff2.png)
![screenshot_2017-10-16-08-35-46](https://user-images.githubusercontent.com/16106413/31610165-76e75e46-b24d-11e7-8a5b-f358f14654cd.png)

**Comment by jsmith** [comment]
Well that's better than I thought. We could maybe add some css and js to render better on mobile!
