### ISSUE TITLE
Code Style in IDEA

### ISSUE THREAD

**Issue by jsmith** [SWE-4103-Group-3/Project#54]
## Issue Description
I think we should create a code style .xml file so which everyone can import into their IDEs. 

## Tasks
- [ ] Create code style settings
- [ ] Export & share .xml file

## Screenshots and Documentation
Information can be found [here](https://www.jetbrains.com/help/idea/configuring-code-style.html)

**Comment by mwalz1** [comment]
Perhaps this could be something we decide in next weeks lab?

**Comment by brandon1024** [comment]
This was fixed https://github.com/SWE-4103-Group-3/Project/pull/65
