### ISSUE TITLE
Course Template Editor Scroll Issue

### ISSUE THREAD

**Issue by brandon1024** [SWE-4103-Group-3/Project#55]
## Issue Description
After creating a course and navigating to it through the course list, if the template has too many rows, the template overflows below the footer, and there is no way to scroll.

Ideally, a course with many rows should be scaled in such a way that the template appears entirely in the current view. In other words, the template should be made to fit the view without the need for scrollbars.

## Steps to Reproduce
- Create a new course with a larger number of rows (around 20)
- Navigate to the template editor by clicking the new course in the course list
- Observe that the template overflows and has no scroll bars.

## Tasks
- [x] Determine the root cause of the issue
- [x] Modify the template so that it is made to fit the view
- [ ] Write tests

## Screenshots and Documentation
![image](https://user-images.githubusercontent.com/22732449/31632220-8a6358c2-b292-11e7-803e-fc6ce5d95c48.png)

**Comment by dsteen338** [comment]
Should this one have a bug label?

**Comment by brandon1024** [comment]
## On this branch:
#### Large Screen (w/ 15x15 grid)
![image](https://user-images.githubusercontent.com/22732449/32128710-a27fdb02-bb56-11e7-8023-ca0b75976204.png)

#### Small Screen  (w/ 15x15 grid)
![image](https://user-images.githubusercontent.com/22732449/32128782-36abf464-bb57-11e7-8719-50757a3c0dbe.png)

#### Large Screen (w/ 5x5 grid)
![image](https://user-images.githubusercontent.com/22732449/32128791-511e1a70-bb57-11e7-81b7-3fb082df7634.png)


#### Small Screen  (w/ 5x5 grid)
![image](https://user-images.githubusercontent.com/22732449/32128788-48ec4408-bb57-11e7-85e8-244d7136d8a6.png)

@dsteen338 @jacsmith21

**Comment by dsteen338** [comment]
It makes sense to have the seats in a more rectangular shape like that to fit the screen for sure. It looks kind of weird but I think it's just because I've always pictured them as squares. The text (showing a student's name or whatever) will probably fit better in a rectangle anyway. Looks good I think

**Comment by jsmith** [comment]
I agree with @dsteen338! Do you think it would be a good idea to create a minimum size for each rectangle?

**Comment by brandon1024** [comment]
@jacsmith21 I agree, that would be a good idea :)

**Comment by brandon1024** [comment]
@jacsmith21 Cells now have a minimum size of 80px x 30px. When the grid is too large, scrollbars are added to display the overflow.

![image](https://user-images.githubusercontent.com/22732449/32136231-b91cb74c-bbe0-11e7-8dbd-776a69be02b0.png)

**Comment by jsmith** [comment]
Perfect that looks great! I'll review the PR sometime soon. Also, do you think it would be a good idea to have a maximum size?

**Comment by brandon1024** [comment]
You mean a maximum class size? If so, definitely but I don’t think it would be something that would fall under this issue.
