### ISSUE TITLE
Using Old Templates

### ISSUE THREAD

**Issue by jsmith** [SWE-4103-Group-3/Project#57]
## Issue Description
As an instructor, I want to be able to choose from a list of recently used templates when creating or editing a course. The current template and the previous template should persist in the database.

This issue description may still need modifications, I am not sure I have all of the requirements for this issue.

## Tasks
- [x] Modify course form so that an instructor may select a previous template (this also includes the JavaScript and backend logic)
- [x] Modify course page so that an instructor may revert to a previous template (this also includes the JavaScript and backend logic)

**Comment by brandon1024** [comment]
So far, instructors can click a button in the course form view to use a seat grid from other course. I've finished implementing UI, all that's left is backend.

##### Progress:
![image](https://user-images.githubusercontent.com/22732449/32473026-d5225232-c33b-11e7-9026-734fa4290949.png)

![image](https://user-images.githubusercontent.com/22732449/32473034-e198f2dc-c33b-11e7-8c5a-fd0b4424d4d9.png)

![image](https://user-images.githubusercontent.com/22732449/32473041-e967da8c-c33b-11e7-9b55-55693840cda4.png)

**Comment by jsmith** [comment]
Looks amazing 👌

**Comment by jacsmith21** [comment]
Testing this now. Everything looks amazing 🔥 🔥 🔥 The only problem is that when I choose a past course I can still input rows / cols (which seem to just be overwritten). Will this be changed with the course validation is fixed?

**Comment by dsteen338** [comment]
This issue was missed in estimating unfortunately, we have added a 13 because of the significant complexity that arose.
