### ISSUE TITLE
Rows & Columns Validation

### ISSUE THREAD

**Issue by jsmith** [SWE-4103-Group-3/Project#60]
## Issue Description
An instructor is able to set the rows and cols of the course to zero.

## Steps to Reproduce
- Login as an instructor
- Create a course with negative rows or cols

## Tasks
- [x] Add validation in the backend
- [x] Set minimum value for row and cols in the frontend

**Comment by dsteen338** [comment]
shoukd this also have an upper bound

**Comment by brandon1024** [comment]
@dsteen338 I think having an upper bound would be a good idea. Mackenzie and I were discussing this earlier, it seems appropriate to set an upper bound of 50 on both rows and columns. A class size of 50*50 is bigger than any lecture hall I've ever heard of, and its unlikely that someone is going to take attendance in a room that big.

**Comment by tonerm43** [comment]
@brandon1024 Mike addressed this in his email to Dr. MacIsaac, not sure if she answered him yet with an appropriate upper bound.

**Comment by mwalz1** [comment]
@tonerm43 
## Update on issue requirements
### Lower Bound
- Will be 1 for row and col.
### Upper Bound
- Will be row and col number of Dineen auditorium + 5 = 18 rows by 31 cols
### Course Name and Section Length
- Both of these entries should be limited to 10 characters.  In addition to this, **please add a helpful suggestion** message to either the prompt, or error message explaining a course code is expected. something like "i.e. SWE4103"  and "i.e. LecA, LecB, LabA, TutC"
