### ISSUE TITLE
Toastr notifications not working

### ISSUE THREAD

**Issue by dsteen338** [SWE-4103-Group-3/Project#73]
## Issue Description
Currently the toastr error messages/ success messages are not working. On course form 
## Steps to Reproduce
- Get a validation error on course form (edit or create)
  - You will not see a validation error

## Tasks
- [ ] Fix toastr messages for course creation/ edit

**Comment by jsmith** [comment]
Could we broaden the scope of this issue to deal with the case when no rows / cols are entered? The current backend validation code we have just throws a null pointer exception.

**Comment by tonerm43** [comment]
The problem here is that all the js got moved to the bottom of the file, so the toastr is getting called before it ever gets brought into the file
