### ISSUE TITLE
Seat State Not Transferring

### ISSUE THREAD

**Issue by jsmith** [SWE-4103-Group-3/Project#74]
## Issue Description
Seat states are not transferring when a new course uses an old template and when a course switches to another course template.

## Steps to Reproduce
- Create a course and change some of the states
then
- Try creating a new course using the previously created template
or
- Create another course then try and using the previously created template

## Tasks
- [x] Find the bug (probably somewhere in the backend)
- [x] Fix the bug

**Comment by dsteen338** [comment]
Is this an issue on develop?

**Comment by jsmith** [comment]
Yeah I think so! It was happening to me. Is that not an issue with you?

**Comment by dsteen338** [comment]
Oh i misunderstood this one actually, haven't tested but probably

**Comment by jsmith** [comment]
Fixed this bug, in the courseReuseHelper method we need:
```java
newSeat.setRow(seat.getRow());
newSeat.setCol(seat.getCol());
newSeat.setState(seat.getState());
newSeat.setCourse(courseReceive); // This line fixed the bug
```

**Comment by jsmith** [comment]
Another issue that was found while fixing this issue was that the row / col input fields were not disappearing in the course form. This was an issue as html ids seem to have been lost while merging:

```html
<div id="course-form-rows" class="md-form">
            <input id="courseRows"  name="rows" type="number" class="form-control" {% if courseCreationError %}value="{{ rowsAmount }}" {% else %} value="{{ course.rows }}" {% endif %}>
            <label for="courseRows">Rows</label>
        </div>
        <div id="course-form-cols" class="md-form">
            <input id="courseCols" name="cols" type="number" class="form-control" {% if courseCreationError %}value="{{ colsAmount }}" {% else %} value="{{ course.cols }}"  {% endif %}>
            <label for="courseCols">Columns</label>
        </div>
```

`course-form-rows` & `course-form-cols` ids were added!

**Comment by dsteen338** [comment]
Oh i thought that one might have been something I did on my pr, guess not.

**Comment by jsmith** [comment]
No I don't think so! I think these may have been caused by my PR merge

**Comment by dsteen338** [comment]
I'm honestly surprised we made it out of the merge conflicts this unscathed
